### ISSUE TITLE
Doubt in networks to be trained in Pretaining vs Unlearning for age prediction in normal_supervised.py  

### ISSUE THREAD

**Issue by surajsrivathsa** [nkdinsdale/Unlearning_for_MRI_harmonisation#1]
Hello,

I am trying to remove contrast and scanner information and predict age from IXI dataset(T1, T2). I had some doubts regarding the code and paper.

1. Could you please let me know if any other preprocessing like skull stripping/bias field removal were used.

2. In papers supplementary section it is mentioned that model is pre trained only on age prediction main task and only during unlearning we use the domain predictor. But in code normal_supervised.py the pertaining consists of both main task and domain predictors. Could you please let me know if I have to use both main prediction and domain predictor in pretaining.

Thanks in advance.

**Comment by nkdinsdale** [comment]
Hello

Sorry for the delay in replying, I was on annual leave.

1. Skull stripping and bias field removal were applied. The data was skull stripped using FSL ANAT and bias field correction was completed using FSL FAST.

2. I would suggest using the main and domain predictor in pretraining. It is not necessary but when we have applied the method to other applications we have found that it increases the stability of the training, especially when using small datasets.

Please let me know if you have any more questions.

Best regards
Nicola

**Comment by surajsrivathsa** [comment]
Thank you for the information, that resolved my doubts.

**Comment by han-yeol** [comment]
Hello, 

I am also interested in your preprocessing process 
I have used fsl_anat
`fsl_anat --nononlinreg --noseg --nosubcortseg -i T1.nii.gz`

is this correct? 
I want to know exactly what you writing

**Comment by nkdinsdale** [comment]
Hi 
Yes I used the T1_to_MNI_lin.nii.gz but the most appropriate outputs to use will depend on the task of interest.

**Comment by han-yeol** [comment]
> 

I am interested in age prediction

as I know, I should use T1_biascorr_brain.nii.gz.
am I wrong? 

Thank you.

**Comment by nkdinsdale** [comment]
yes sounds sensible. we showed in our neuroimage paper (https://www.sciencedirect.com/science/article/pii/S1053811920311745) that the use of nonlinear registered data supressed age information
