### ISSUE TITLE
Small data size & gradient backward problem

### ISSUE THREAD

**Issue by 1pha** [nkdinsdale/Unlearning_for_MRI_harmonisation#3]
Hi, I'm trying to run your code and encountered some troubles. I'm doing the age prediction task (not the segmentation) and I got -
1. Small Input size
I see that your Encoder model has 6 max poolings and the image size of (128, 128, 32) would hardly feedforward to the Encoder... I temporarily made it 64 to make it work but still, I get ...
2. train_unlearn_three_datasets / valid_unlearn_three_datasets
We need to update the Encoder twice from two optimizers/loss - loss from age, and confusion loss. I saw your setups there and tried to replicate the result and what I encounter is 
```
Traceback (most recent call last):
  File "normal_supervised.py", line 227, in <module>
    loss, acc, dm_loss, conf_loss = train_unlearn_threedatasets(args, models, train_dataloaders, optimizers, criterions, epoch), criterions, epoch)                                                                                       n_unlearn_threedatasets
  File "G:\My Drive\brain_data\workspace\Unlearning_for_MRI_harmonisation\train_utils.py", line 88, in train_unlearn_threedatasets
    loss_conf.backward(retain_graph=False)
  File "C:\Users\pha\anaconda3\envs\cnn\lib\site-packages\torch\tensor.py", line 221, in backward          d
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "C:\Users\pha\anaconda3\envs\cnn\lib\site-packages\torch\autograd\__init__.py", line 130, in backwarn: [torch.cuda.FloatTensor [384, 96]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection d
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [384, 96]], which is output 0 of TBackward, is at version 2; expected version 1 
instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```
this is the error encounter both from your open source code and my replicated code... The error comes out from ... train_utils.py > train_unlearn_three_datasets() - line64-88
```
            # First update the encoder and regressor
            optimizer.zero_grad()
            features = encoder(data)
            output_pred = regressor(features)
            loss_1 = criteron(output_pred[:n1], target[:n1])
            loss_2 = criteron(output_pred[n1:n1+n2], target[n1:n1+n2])
            loss_3 = criteron(output_pred[n1+n2:], target[n1+n2:])
            loss = loss_1 + loss_2 + loss_3
            loss_total = loss
            loss_total.backward(retain_graph=True)
            optimizer.step()

            # Now update just the domain classifier
            optimizer_dm.zero_grad()
            output_dm = domain_predictor(features.detach())
            loss_dm = args.alpha * domain_criterion(output_dm, domain_target)
            loss_dm.backward()
            optimizer_dm.step()

            # Now update just the encoder using the domain loss
            optimizer_conf.zero_grad()
            output_dm_conf = domain_predictor(features)
            loss_conf = args.beta * conf_criterion(output_dm_conf, domain_target)        # Get rid of the weight for not unsupervised
            loss_conf.backward(retain_graph=False)
            optimizer_conf.step()
```
Can you give an idea about these issues? I really like the idea of giving confusion loss to the encoder to get rid of scanner information I do wish to replicate this. Thank you :)

**Comment by nkdinsdale** [comment]
Hi, 
1. It is small but on the GPU implementation of the  code with the version of pytorch the last dimension becomes 1 and so the model works. We found the depth helped but you could just remove a pooling layer if its an issue?

2. That looks  like  its because of the model architecture - maybe you have a ReLU(inplace=true) or similar? In place leads to the graph not being stored. Can you see anything like that in the model?

**Comment by 1pha** [comment]
Thank you for replying.
1. Oh I didn't notice that. Um, are those codes that control those last dimensions on GitHub as well? If it is, can you specify where they are?
2. Actually I was using your open-source code trying to minimize any retouch from my side. That inplace=True was happening on the source code and I made everything false but the same error just happens again! Can you tell me how you resolved this? 
![image](https://user-images.githubusercontent.com/62973169/120881459-25bd4400-c60c-11eb-8723-6deac828184a.png)
![image](https://user-images.githubusercontent.com/62973169/120881548-d592b180-c60c-11eb-9f66-76d3ed45f1c6.png)

Thank you 🙏

**Comment by nkdinsdale** [comment]
Hi
Sorry for the slow reply, Im writing my thesis so its a bit hectic. Which pytorch version are you using? I havent tested the code for any but the reported version, wondering if that could be the problem? (I never got this error so if you havent changed the code Im not sure what the issue is..) 
Best
Nicola
